//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourceProject {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class About {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal About() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResourceProject.About", typeof(About).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reason for notes is so you can look back and see what and how.  The better the note the better you&apos;ll you history will be
        ///                                    &lt;br /&gt;
        ///                                    Digi note allows you to go back and look at all you previous  notes and see what you&apos;ve done, split into each category and how long it took.
        /// </summary>
        public static string HistoryContent {
            get {
                return ResourceManager.GetString("HistoryContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The history.
        /// </summary>
        public static string HistoryTitle {
            get {
                return ResourceManager.GetString("HistoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This allows you take your note in ease.  Each note can be split into categories, so you can keep track easily.
        ///                                &lt;ul style=&quot;text-align:left; font-size:12px;  list-style-type: none;&quot;&gt;
        ///                                    &lt;li&gt; &lt;b&gt;Categories and Sub categories&lt;/b&gt;&lt;/li&gt;
        ///                                    Task through the day may vary and keeping detail notes may be a difficult.  But by spliting them into categories and sub categories it makes it easier.  
        ///                       [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NotesContent {
            get {
                return ResourceManager.GetString("NotesContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taking and store notes.
        /// </summary>
        public static string NoteTitle {
            get {
                return ResourceManager.GetString("NoteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a Click once application.  Once installed, if there is an internet conenction it will check for an update.
        ///                If found it will ask if you want to update or not.  Once you accept it will automatically update you application..
        /// </summary>
        public static string PageDescriptionBottom {
            get {
                return ResourceManager.GetString("PageDescriptionBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digi notes is a windows desktop application, which is a complet note and task managment solution roled into one..
        /// </summary>
        public static string PageDescriptionTop {
            get {
                return ResourceManager.GetString("PageDescriptionTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Application.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your day to day To-Do list may grow and grow for a project or just little small task and it may be a nightmare to keep track.
        ///                                    &lt;br /&gt;
        ///                                    Digi notes has a Agile To-Do list function built in and it could make your To-Do list more workable.
        ///                                    &lt;ul style=&quot;text-align:left; font-size:12px; ;  list-style-type: none;&quot;&gt;
        ///                                        &lt;li&gt;&lt;b&gt;Categorized To-Do list (Planned, Started, Testi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TaskContent {
            get {
                return ResourceManager.GetString("TaskContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agile task list.
        /// </summary>
        public static string TaskTitle {
            get {
                return ResourceManager.GetString("TaskTitle", resourceCulture);
            }
        }
    }
}
